### ISSUE TITLE
When will the code of Neural Ilt 2.0 be open-sourced

### ISSUE THREAD

**Issue by liurongfang** [cuhk-eda/neural-ilt#1]
Hi @liulixinkerry , thank you for your work,  I see the paper "Neural Ilt 2.0" is released that add L_epe_fast loss as DSR term , how is EPE computing implemented? and when will the code of Neural Ilt 2.0 be open-sourced？

**Comment by InfamousMeGa** [comment]
Hi @liurongfang , the epe calculation is based on the following paper:
"ICCAD-2013 CAD contest in mask optimization and benchmark suite" (https://ieeexplore.ieee.org/document/6691131).

I have updated the code for epe support in the branch: "tcad_epe_version", please try. Thx.

**Comment by qipan0323** [comment]
Hi @InfamousMeGa, thank you for your work. We successfully reproduced your experiment, but the "shot count" in the paper "Neural-ILT" does not appear, when will this part of the code be open-sourced? Or where can we find it?

**Comment by InfamousMeGa** [comment]
> Hi @InfamousMeGa, thank you for your work. We successfully reproduced your experiment, but the "shot count" in the paper "Neural-ILT" does not appear, when will this part of the code be open-sourced? Or where can we find it?

Hi @qipan0323, thanks for your interests in Neural-ILT.
The "shot count" of each mask image requires a seperated mask fracturing tool, whose core algorithms (polygon decomposition) & implementations do not belong to Neural-ILT, so it won't be open-sourced here. We appreaciate your understanding.

Instead, would you mind send the mask image files that you want to verfiy to me (btjiang@cse.cuhk.edu.hk)? I can run the mask fracutring for those mask images on my side, and the following items (for each mask image) will be returned to you:
1) mask fracturing results (shot count & runlog);
2) a gds file of the fractured mask (you can open it via KLayout).

Thanks,
-Bentian
